# Generated by Django 3.1.14 on 2021-12-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineInfoKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300)),
                ('institution', models.CharField(max_length=300)),
                ('institution_website', models.URLField(max_length=800)),
                ('author_phone', models.CharField(max_length=20, null=True)),
                ('author_email', models.EmailField(max_length=254)),
                ('date_of_research', models.DateField()),
                ('research_title', models.CharField(max_length=800)),
                ('research_link', models.URLField(max_length=2000)),
                ('notes', models.TextField()),
                ('keywords', models.ManyToManyField(to='core.VaccineInfoKeywords')),
            ],
        ),
    ]
