# Generated by Django 3.1.14 on 2021-12-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineinfokeywords',
            name='keyword',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
